# Generated by Django 4.0.4 on 2022-06-09 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=30, null=True)),
                ('surname', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=30)),
                ('cvv', models.CharField(max_length=3)),
                ('placeholder_name', models.CharField(max_length=80, null=True)),
                ('bank_name', models.CharField(max_length=20)),
                ('expiration_date', models.CharField(max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='florataba_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=30, null=True)),
                ('itn', models.CharField(max_length=30, null=True)),
                ('place_issue', models.CharField(max_length=20)),
                ('expiration_date', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='florataba_api.user')),
            ],
        ),
    ]
