# Generated by Django 4.0.5 on 2022-06-12 21:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=32)),
                ('event_type_bouquet', models.CharField(choices=[('Wedding', 'Wedding'), ('Birthday', 'Birthday'), ("Valentine's Day", "Valentine's Day"), ('Funeral', 'Funeral'), ('Single', 'Single')], default='Single', max_length=36)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_single_bouquet', models.BooleanField(default=True)),
                ('available_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('img_url', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(50, 'Gold'), (5, 'Start'), (15, 'Family'), (20, 'Volunteer')])),
                ('benefits_text', models.CharField(max_length=255)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(blank=True, max_length=64, null=True)),
                ('region', models.CharField(blank=True, max_length=32, null=True)),
                ('build_number', models.CharField(max_length=10)),
                ('apartment_number', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, choices=[('News', 'News'), ('Orders', 'Orders'), ('Discounts', 'Discount')], max_length=50, null=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.location')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.discount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('surname', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(max_length=20)),
                ('_User__password', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(5)])),
                ('details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('placeholder_name', models.CharField(max_length=80, null=True)),
                ('bank_name', models.CharField(max_length=20)),
                ('expiration_date', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.userdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_info', models.CharField(max_length=255, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Collecting', 'Collecting'), ('En route', 'In Way'), ('Done', 'Done'), ('Processed', 'Processed')], max_length=50)),
                ('order_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='domain.orderdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
