# Generated by Django 4.0.5 on 2022-06-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_alter_bouquet_options_alter_discount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='domain.orderdetails'),
        ),
    ]
