# Generated by Django 4.0.5 on 2022-06-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_alter_order_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='details_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.userdetails'),
        ),
    ]
